// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { env } from "node:process";
// import { DATABASE_URL, DIRECT_URL } from "./src/configs/envs"; 
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env.DIRECT_URL, // Use the direct connection URL for migrations
  },
});
